[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_staking_program = "FvBdLVZv2FTBdCcNgsJCYHpQ9PCDyKVumRSQaZuSGJHi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dima/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
